### ISSUE TITLE
[Logging] Strip bash colors from the log string

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-gelato-relay-service#36]
@diegopazosrego says Datadog is receiving logs with a control characters in the beginning which Datadog doesn't like.

**Comment by diegopazosrego** [comment]
Yes the logs that we are receiving are:
` [34mdebug[39m: [34m2023-03-23T10:51:29.076Z ad89578f-a10a-4d66-ad29-5462e5c1bde0 - [==>] GET /v1/relay/health/[39m
[32minfo[39m: [32m2023-03-23T10:51:29.077Z ad89578f-a10a-4d66-ad29-5462e5c1bde0 - [<==] 200  [39m
[34mdebug[39m: [34m2023-03-23T10:51:29.077Z e6bc8562-e213-4ccc-b92f-762d29a29b3d - [==>] `

As you can see, every line starts with `[34m` or `[32m` and ends with `[39m `, which means that those codes are the terminal colors in hexadecimal.

**Comment by diegopazosrego** [comment]
All good @katspaugh @schmanu! Thank you 🙌

**Comment by diegopazosrego** [comment]
Hi, 
we have in error logs some colors in hexadecimal:
`debug: 2023-03-28T16:05:26.908Z 06ce975a-9402-4b35-8368-6e7e27820ac0 - [==>] POST /v1/relay
[31m[Nest] 1  - [39m03/28/2023, 4:05:26 PM [31m  ERROR[39m [38;5;3m[ExceptionsHandler] [39m[31mdata out-of-bounds (buffer=0x00000000000000000000000000000000000000000000, length=22, offset=32, code=BUFFER_OVERRUN, version=6.0.5)[39m
RangeError: data out-of-bounds (buffer=0x00000000000000000000000000000000000000000000, length=22, offset=32, code=BUFFER_OVERRUN, version=6.0.5)
    at makeError (/node_modules/ethers/lib.commonjs/utils/errors.js:118:21)
    at assert (/node_modules/ethers/lib.commonjs/utils/errors.js:138:15)
    at #peekBytes (/node_modules/ethers/lib.commonjs/abi/coders/abstract-coder.js:364:39)
    at Reader.readBytes (/node_modules/ethers/lib.commonjs/abi/coders/abstract-coder.js:379:36)
    at Reader.readIndex (/node_modules/ethers/lib.commonjs/abi/coders/abstract-coder.js:389:46)
    at BytesCoder.decode (/node_modules/ethers/lib.commonjs/abi/coders/bytes.js:23:40)
    at BytesCoder.decode (/node_modules/ethers/lib.commonjs/abi/coders/bytes.js:35:46)
    at /node_modules/ethers/lib.commonjs/abi/coders/array.js:71:31
    at Array.forEach (<anonymous>)
    at unpack (/node_modules/ethers/lib.commonjs/abi/coders/array.js:65:12)`
    
    You may need to configure another parameter.

**Comment by iamacook** [comment]
> Hi, we have in error logs some colors in hexadecimal: `debug: 2023-03-28T16:05:26.908Z 06ce975a-9402-4b35-8368-6e7e27820ac0 - [==>] POST /v1/relay �[31m[Nest] 1 - �[39m03/28/2023, 4:05:26 PM �[31m ERROR�[39m �[38;5;3m[ExceptionsHandler] �[39m�[31mdata out-of-bounds (buffer=0x00000000000000000000000000000000000000000000, length=22, offset=32, code=BUFFER_OVERRUN, version=6.0.5)�[39m RangeError: data out-of-bounds (buffer=0x00000000000000000000000000000000000000000000, length=22, offset=32, code=BUFFER_OVERRUN, version=6.0.5) at makeError (/node_modules/ethers/lib.commonjs/utils/errors.js:118:21) at assert (/node_modules/ethers/lib.commonjs/utils/errors.js:138:15) at #peekBytes (/node_modules/ethers/lib.commonjs/abi/coders/abstract-coder.js:364:39) at Reader.readBytes (/node_modules/ethers/lib.commonjs/abi/coders/abstract-coder.js:379:36) at Reader.readIndex (/node_modules/ethers/lib.commonjs/abi/coders/abstract-coder.js:389:46) at BytesCoder.decode (/node_modules/ethers/lib.commonjs/abi/coders/bytes.js:23:40) at BytesCoder.decode (/node_modules/ethers/lib.commonjs/abi/coders/bytes.js:35:46) at /node_modules/ethers/lib.commonjs/abi/coders/array.js:71:31 at Array.forEach (<anonymous>) at unpack (/node_modules/ethers/lib.commonjs/abi/coders/array.js:65:12)`
> 
> You may need to configure another parameter.

It turns out this needs be [disabled by a arbitrary `NO_COLOR` env. var](https://docs.nestjs.com/techniques/logger). Can you set it to a non-empty string value on the DevOps side?

![image](https://user-images.githubusercontent.com/20442784/228812683-e76bbe7e-948f-435f-ad44-a870971ee7ef.png)

**Comment by iamacook** [comment]
@diegopazosrego has confirmed that this was solved.
